INSERT INTO materia(id, nombre) VALUES
(1, 'Derecho Administrativo'),
(2, 'Derecho Constitucional'),
(3, 'Derecho Comercial'),
(4, 'Derecho Corporativo'),
(5, 'Propiedad Intelectual'),
(6, 'Derecho de Autor'),
(7, 'Derecho Civil'),
(8, 'Derecho Laboral'),
(9, 'Derecho Migratorio'),
(10, 'Condominios'),
(11, 'Derecho Sucesoral'),
(12, 'Asociaciones Sin Fines de Lucro'),
(13, 'Derecho Ambiental'),
(14, 'Derecho Inmobiliario'),
(15, 'Otras Materias'),
(16, 'Descarga de Documentos Modelo');